version: "3.8"

services:
  backend:
    build: ../bookstore-back     
    container_name: bookstore-back
    ports:
      - "8080:8080"
  frontend:
    build: .                       
    container_name: bookstore-front
    command: npm run dev            
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:                     
      - /app/node_modules           